SecondDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('control/', admin.site.urls),
    path('app/', include('app.urls'))
]

app/urls.py
from django.urls import path


from . import views

app_name = 'app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

app/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.


class Questions(models.Model):

    """
    问题模型，
    每个类都是django.db.models.Model的子类
    每个字段都是Field类的实例
    每个Field实例的名字就是字段名字，数据库会把这个值作为表的列名
    可以在每个Field中使用一个可选的第一位置参数用于提供一个人类可读的字段名
    将作为文档的一部分
    """

    def __str__(self):
        return self.question_text

    question_text = models.CharField("问题名称", max_length=200)
    pub_data = models.DateTimeField("发布日期")

    def was_published_recently(self):
        """
        判断问卷是否最近时间发布
        :return: 如果是返回True，如果不是返回False
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_data <= now


class Choice(models.Model):

    """
    选项模型
    使用ForeignKey定义了一个外键关系。它告诉Django，每个Choice关联到
    一个对应Question，注意：将外键写在“多”的一方，
    Django支持通用的数据关系：一对一，一对多，多对多
   """
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

app/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Questions, Choice


class IndexView(generic.ListView):
    template_name = 'app/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Questions.objects.order_by('-pub_data')[:5]


class DetailView(generic.DetailView):
    model = Questions
    template_name = 'app/detail.html'
    context_object_name = "question"


class ResultsView(generic.DetailView):
    model = Questions
    template_name = 'app/results.html'
    context_object_name = "question"


def vote(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'app/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('app:results', args=(question.id,)))

app/templates/app/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</body>
</html>

app/templates/app/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'app:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

app/templates/app/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'app:detail' question.id %}">Vote again?</a>
</body>
</html>